### ISSUE TITLE
Feature Request: terminal as drag and droppable pane item

### ISSUE THREAD

**Issue by schlichtanders** [platformio/platformio-atom-ide-terminal#198]
Dear platformio team,

Sometimes the fixed bottom pane the current terminal gets in the way...
It would be awesome if one could drag and drop the terminal pane into a different place (enabling right, left, top, down split views)

Do you think something like this is reasonable/possible?

**Comment by masolnada** [comment]
+1

**Comment by aecorredor** [comment]
+1

**Comment by keweili** [comment]
For a widescreen laptop, it is better to have a terminal on the right, not the bottom. no space there

**Comment by danielcrane** [comment]
+1
I love this package, but it's useless to me if the panel can only be at the bottom. In my case, having it on the right side would be ideal.

**Comment by the-j0k3r** [comment]
@danielcrane all such contributions are user generated, so its unlikely to be seen any time soon since #543,
 
You could try https://github.com/jsmecham/atom-terminal-tab its a node-pty-prebuilt + xterm.js so a modern though basic pseudo terminal implementation. (what  this project should be based on see  #426) you can place that terminal anywhere you like, 

Its not for me, its not configurable, doesnt support things I use daily, though it may suit you/others better.

**Comment by contang0** [comment]
+1

**Comment by the-j0k3r** [comment]
Please see https://github.com/platformio/platformio-atom-ide-terminal/pull/697 Pull request, it adds this feature. (Well it displays in Dock and optionally as is.)

Needs testing and feedback to dev.

Its OK to reply in PR if you have actual feedback on testing along with any details of your findings.

Thanks.

**Comment by the-j0k3r** [comment]
This has been fixed in https://github.com/bus-stop/terminus

**Comment by contang0** [comment]
@the-j0k3r , thank you for continuing the work on this!

**Comment by chrisfranko** [comment]
> This has been fixed in https://github.com/bus-stop/terminus

Dude, thank you so much for this. I cant tell you how many times I used the other terminal and was like... wwhhyyyy cant I drag this to the right. This makes the experience soooo much nicer imo.

**Comment by sakkyakei** [comment]
> > This has been fixed in https://github.com/bus-stop/terminus
> 
> Dude, thank you so much for this. I cant tell you how many times I used the other terminal and was like... wwhhyyyy cant I drag this to the right. This makes the experience soooo much nicer imo.

Could you please help to advise how to enable this ? I still cannot find it.
Thanks!!!

**Comment by UziTech** [comment]
Go to https://atom.io/packages/x-terminal and install that package then you should be able to drag terminals to any dock or pane

![X-Terminal moving terminals demo](https://cdn.statically.io/gh/bus-stop/x-terminal/master/resources/x-terminal-moving-terminals-demo.gif)

**Comment by sakkyakei** [comment]
> Go to https://atom.io/packages/x-terminal and install that package then you should be able to drag terminals to any dock or pane
> 
> ![X-Terminal moving terminals demo](https://camo.githubusercontent.com/73a94ad3aa4b8b67d84ca8ea7b5166eb84669411c5e4758ba0331aaf238fb262/68747470733a2f2f63646e2e737461746963616c6c792e696f2f67682f6275732d73746f702f782d7465726d696e616c2f6d61737465722f7265736f75726365732f782d7465726d696e616c2d6d6f76696e672d7465726d696e616c732d64656d6f2e676966)

THANK YOU SOOOOOOOOO MUCH !!!
