### ISSUE TITLE
Some installed packages could not be loaded because they contain native modules that were compiled for an earlier version of Atom.Rebuild Packages Package Settings

### ISSUE THREAD

**Issue by Excelsior-WYH** [platformio/platformio-atom-ide-terminal#338]
platformio-ide-terminal 2.5.5

bin@unknown – Cannot find module '/Users/dannier/.atom/packages/platformio-ide-terminal/node_modules/pty.js/bin'
bin@unknown – Cannot find module '/Users/dannier/.atom/packages/platformio-ide-terminal/node_modules/pty.js/bin'
bin@unknown – Cannot find module '/Users/dannier/.atom/packages/platformio-ide-terminal/node_modules/pty.js/bin'
bin@unknown – Cannot find module '/Users/dannier/.atom/packages/platformio-ide-terminal/node_modules/pty.js/bin'
bin@unknown – Cannot find module '/Users/dannier/.atom/packages/platformio-ide-terminal/node_modules/pty.js/bin'
bin@unknown – Cannot find module '/Users/dannier/.atom/packages/platformio-ide-terminal/node_modules/pty.js/bin'
bin@unknown – Cannot find module '/Users/dannier/.atom/packages/platformio-ide-terminal/node_modules/pty.js/bin'
bin@unknown – Cannot find module '/Users/dannier/.atom/packages/platformio-ide-terminal/node_modules/pty.js/bin'

**Comment by beneon** [comment]
I tried rebuild several times and this time somehow it worked...
maybe you should update your node-gyp and ...
sorry I really don't know how I got it to work but the problem can be fixed, keep on trying!

**Comment by semi-xi** [comment]
the same problem~ORZ

**Comment by LeaVerou** [comment]
Same here

Edit: Fixed by rebuilding packages.

**Comment by aaronbarker** [comment]
Took me a while to figure out how to rebuild packages, so sharing for others who follow.

There was a red bug in the bottom toolbar, click it.  This opened a new window/tab saying there was a problem with this package and had a `rebuild packages` button.  I clicked it, it did it's thing. I closed the window, restarted, still a problem.  I did the above again and this time noticed that the button was replaced with a `restart atom` button (may have missed it the first time, but if not, you may need to try multiple times).  After the restart, things were working again.

Hope that helps others :)

**Comment by semi-xi** [comment]
@aaronbarker well! it do as well as before. thanks for solving the problem^_^

**Comment by ivankravets** [comment]
https://github.com/platformio/platformio-atom-ide-terminal/issues/297
