### ISSUE TITLE
Uncaught Error: channel closed

### ISSUE THREAD

**Issue by aldaaga** [platformio/platformio-atom-ide-terminal#350]
events.js:160
![error](https://user-images.githubusercontent.com/29460165/29731165-0cdce9e8-89a9-11e7-8b7a-f04b27a8d1fd.PNG)

Doesn't let me you use terminal on Atom. What should I do? Anyone faced this problem before?

**Comment by AlfieDarko** [comment]
I got this problem today

**Comment by aldaaga** [comment]
anyone any suggestion how to work this out?

**Comment by EswarJ** [comment]
+1

**Comment by mrhBU67** [comment]
Same with me.  I'm new to this so any help is appreciated.

**Comment by Sanil14** [comment]
same. How can i fix this.

**Comment by hellbenthorse** [comment]
I've also had the same error happen. Running Windows 10 x64. have tried in the 32 bit version of Atom and still the same problem persists.

I've also tried swapping default shell's from cmd to powershell and back to no avail.

Have installed/reinstalled C++ libraries, build tools etc and can't get around it at present.

Very interested in finding a fix for this.

**Comment by clehmberg** [comment]
Just leaving a mark here... same issue. Please resolve

**Comment by Lalit12289** [comment]
Same with me. I'm new to this so any help is appreciated.

**Comment by GeorgeBurac** [comment]
Same

**Comment by asadkamal** [comment]
Having the same issue. Really new to atom, so not sure what to do. 

Thanks

**Comment by npabbisetty** [comment]
Seeing the same issue with Windows10 and Atom.

**Comment by hellbenthorse** [comment]
Update: I still get the error sometimes when opening a terminal in atom. However I've noticed ignoring the error the first couple of times and then when opening a new terminal if i begin typing in the terminal as soon as it initializes it will work. All future terminal instances in that atom session will also function without issue. 

I don't have a fool proof  way of replicating this at present as it seems to be random but random seldom is. I don't possess the technical knowledge presently to pin point it.

**Comment by thbui** [comment]
This issue come up again and again every time PlatformIO is updated.

**Comment by RayTimlin** [comment]
Having same problem in windows 10

**Comment by naziasc** [comment]
also having the same issue, is there a fix found for this issue

**Comment by EdgarDelaRosa** [comment]
Same 👎

**Comment by ShivaShankarPuvvada** [comment]
same here

**Comment by Freekdirkx** [comment]
same here

**Comment by MichFe** [comment]
Same issue, someone managed to solve it?

**Comment by concon121** [comment]
Resolved on my windows 10 box.  Appears to be an issue with node-gyp building some native extensions for pty.js.  Its a bit of a faff to fix, but here it is anyway:

1. Open up cmd.exe as admin
2. npm install --global --production windows-build-tools
3. Uninstall platformio-ide-terminal
4. Reboot PC
5. Reinstall platformio-ide-terminal
6. cd ~/.atom/packages/platformio-ide-terminal/node_modules/pty.js
7. node scripts\install.js

You should see in the terminal the native extensions being build correctly, it prints a lot of junk out to the console but you're looking for:

```
 Generating code
  Finished generating code
  pty.vcxproj -> C:\Users\<userid>\.atom\packages\platformio-ide-terminal\node_modules\pty.js\build\Release\\pty.node
  pty.vcxproj -> C:\Users\<userid>\.atom\packages\platformio-ide-terminal\node_modules\pty.js\build\Release\pty.pdb (Full PDB)
```

After that just restart atom and you're all set with a working terminal!

**Comment by erkobg** [comment]
Should be "npm install --global --production windows-build-tool**s**"   , right?

**Comment by concon121** [comment]
Yeah sorry I was half asleep when I wrote that, edited and updated my comment for future readers. Cheers!

**Comment by hellbenthorse** [comment]
@concon121 Thanks your wisdom mate, fixed it right up. Cheers!

**Comment by kmohan10** [comment]
Here is what worked for me:
Settings - Install Packages - Search for platformio-ide-terminal

Since the package is already installed, select 'Uninstall'.

Close Atom - Reopen Atom

Back to Install Packages and re-install platformio-ide-terminal

Hope it works to you as well.  I am using Windows 7 (64-bit) system.

**Comment by tatsu100311** [comment]
@concon121 Thank you very much, your kind comment. I also fixed my bug!
However, I have some troubles to fix the bug in my condition. So, I write what I did for someone's help.
(I am using Windows 10 (64-bit). I guess only Windows users are in trouble with this bug.)

If your local language is not English, you may get error to do `node scripts\install.js`. I got error.
In that case, please look this [@jfhenriques's comment](https://github.com/nodejs/node-gyp/pull/366#issuecomment-47416841), and do `npm install node-gyp -g`.
Then, retry `node scripts\install.js`, it will be successful this time.

Thanks.

**Comment by erkobg** [comment]
Unfortunately for me any of these instructions don't work. 
Windows 10 (64) ...
Any other ideas?

**Comment by concon121** [comment]
@erkobg do you get a stack trace or anything printed out to the developer console that could help us debug the issue?

**Comment by erkobg** [comment]
In the Dev Console I see:
`events.js:106 A dynamic link library (DLL) initialization routine failed.
\\?\C:\Users\MY_USER\.atom\packages\platformio-ide-terminal\node_modules\pty.js\build\Release\pty.node
(anonymous) @ <embedded>:72772
(anonymous) @ <embedded>:72849
module.exports.Emitter.simpleDispatch @ <embedded>:64068
module.exports.Emitter.emit @ <embedded>:64184
(anonymous) @ <embedded>:72801
emitTwo @ events.js:106
emit @ events.js:191
process.nextTick @ internal/child_process.js:752
_combinedTickCallback @ internal/process/next_tick.js:67
_tickCallback @ internal/process/next_tick.js:98
events.js:106 Objectcode: "ENOENT"errno: -4058path: "C:\Users\MY_USER\.atom\packages\platformio-ide-terminal\node_modules\pty.js\bin\win32\x64_m53\pty.node.bak"syscall: "lstat"__proto__: Object
(anonymous) @ <embedded>:72775
(anonymous) @ <embedded>:72849
module.exports.Emitter.simpleDispatch @ <embedded>:64068
module.exports.Emitter.emit @ <embedded>:64184
(anonymous) @ <embedded>:72801
emitTwo @ events.js:106
emit @ events.js:191
process.nextTick @ internal/child_process.js:752
_combinedTickCallback @ internal/process/next_tick.js:67
_tickCallback @ internal/process/next_tick.js:98
`

**Comment by surajgampa** [comment]
@concon121  Of your 7 step solution, after step 5, I still get the same error in the terminal and I'm not able to run the 6th and 7th step in it (doesn't allow to enter any text). Kindly help. Mine is a Windows 10 (64).

**Comment by h3rmanj** [comment]
Got this error when on W10 1703, upgrading to 1709 seems to have fixed it.

**Comment by abhirathod07** [comment]
I've got the same error, can anyone help please...

**Error: channel closed
    at ChildProcess.target.send (internal/child_process.js:548:16)**

**Comment by lffg** [comment]
Same. Bump.

**Comment by antonapua** [comment]
same.

**Comment by 1985michel** [comment]
me too W10 64

**Comment by erkobg** [comment]
Hello,
Windows 10 64 here.
after checking the referenced issue https://github.com/jeremyramin/terminal-plus/issues/280
I was able to fix the issue by doing following :
1. Closed PlatformIO
2. Open CMD 
2. Navigate to `C:\Users\USERNAME\.atom\packages\platformio-ide-terminal` (eg. **CD `C:\Users\USERNAME\.atom\packages\platformio-ide-terminal`** )
3. type **npm install** and wait to complete
4. type **apm rebuild** and wait to complete
5. Start PlatformIO
6. Try any Serial Monitor or "Upgrade platforms, packages and libraries"
( it can give the same error first time, ignore and start Serial Monitor or "Upgrade platforms, packages and libraries" again, second time) 

Hope this helps.

**Comment by collins73** [comment]
Same issue here..

**Comment by ElecTreeFrying** [comment]
for windows

run atom as administrator
close atom
then run atom normally not as an administrator

**Comment by davelopeer** [comment]
Did anyone manage to run it properly? I tried but wasn't able to run it on Atom. I use Windows 10. 

I tried the npm install (...) but my prompt didn't reconize it

**Comment by edivaldodelgado** [comment]
@Barenco I was able to do what @erkobg did and it worked. You have to install node.js first.

[https://nodejs.org/en/]

After that, try the steps again.

**Comment by erkobg** [comment]
Well, testing from a long time so far ... issue tends to come over and over again.... it is really annoying ... I used to ignore it somehow so far but in long term it would be better if they fix the issue from the root...

**Comment by edivaldodelgado** [comment]
@erkobg that's true. In fact, I had some troubles with conda virtual environments after, then I decide to use cmd itself, in another windows.

**Comment by davelopeer** [comment]
@edivaldodelgado indeed it work! Thank you guys!

**Comment by ghost** [comment]
I have a "Uncaught Error: channel closed"
 event.js.160
my OS is win 10

**Comment by buttrs2013** [comment]
also having this error, have followed all the various instructions in this thread but to no avail. does anyone have any other ideas?

**Comment by the-j0k3r** [comment]
Please retest again with platformio-atom-ide-terminal 2.9.0 is using node-pty-prebuilt instead unmaintained and outdated pty.js
