### ISSUE TITLE
Module build failed: Error: "extract-text-webpack-plugin" loader is used without the corresponding plugin

### ISSUE THREAD

**Issue by jspecter** [platformio/platformio-atom-ide-terminal#452]
```javascript
PS D:\Projects_BK\BKWeiXinClient> npm run dev

> bk_seal@1.0.0 dev D:\Projects_BK\BKWeiXinClient
> webpack-dev-server --inline --progress --config build/webpack.dev.conf.js
                                                                                     46% building modules 304/304 modules 0  75% advanced
Build completed in 25.754s

ERROR  Failed to compile with 27 errors                                                                                         13:58:59
 
error  in ./src/pages/seal/apply-list.vue

Module build failed: Error: "extract-text-webpack-plugin" loader is used without the corresponding plugin, refer to https://github.com/we
bpack/extract-text-webpack-plugin for the usage example
    at Object.pitch (D:\Projects_BK\BKWeiXinClient\node_modules\extract-text-webpack-plugin\dist\loader.js:57:11)

 @ ./src/pages/seal/apply-list.vue 2:2-614
 @ ./src/router/index.js
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./src/main.js
```
---
i am the new user for atom,i want to run application with vue and webpack,when i use cl `run dev server` with `platformio-ide-terminal`,and the error occured above,but when i use other ide like webstorm  or cmd  on windows 10 ,app can run normally and auto-open-browser,any idea for this error?

**Comment by HTML-Worker** [comment]
I also met this problem. Have you solved it?

**Comment by ilhamsa1** [comment]
Please anyone , solved this issue please ?

**Comment by cheng531jiang** [comment]
I also met this problem. I fixed it by changing the platform-ide-terminal setting.
In platform-ide-terminal settings->core->auto run command, add set NODE_PATH=&&set NODE_ENV=.
Then it works.

**Comment by wuweiyan2012** [comment]
Just the same for me!   
Anyone solved this problem?

**Comment by descodifica** [comment]
The problem persists. It's frustrating to have a terminal and not be able to use it!

**Comment by descodifica** [comment]
Resolved

Add in Auto Run Command of the Platformio Ide Terminal settings:

$env:NODE_ENV="development"

**Comment by the-j0k3r** [comment]
Please retest again with platformio-atom-ide-terminal 2.9.0.
These type issues all so far seem fixed with this release due to using node-pty-prebuilt instead unmaintained and outdated pty.js

if issues persist open a new ticket with required information.

Thx =)
