### ISSUE TITLE
Unable to finish the download of platformio-ide - atom dependencies 

### ISSUE THREAD

**Issue by pbj92** [platformio/platformio-atom-ide-terminal#594]
![atom dependencies](https://user-images.githubusercontent.com/42799016/44773515-14989c00-ab71-11e8-9c4d-61339c001003.jpg)

I can't get further with the download - It have been running for 2 hour straight and nothing seems to happen. 
Any advice on how I can solve this?

**Comment by the-j0k3r** [comment]
@pbj92 Hi.

I can suggest you disable the firewall and test, also consider that the server itself (https://atom.io/packages) may be experiencing problems could be routing or something else), it already did have some issues not long ago, which were resolved eventually.

**Comment by Havolture** [comment]
I have the same problem installing PlatformIO IDE as pbj92. Disabling the Firewall did not solve it.

**Comment by chsafouane** [comment]
I also have the same problem and I disabled the firewall. Yet, the problem still persist

**Comment by the-j0k3r** [comment]
I dont think there anything the project owner can do, this seems external to the project.

@ivankravets thoughts?

**Comment by ivankravets** [comment]
Duplicate of https://github.com/noseglid/atom-build/issues/569

**Comment by ivankravets** [comment]
More and more developers abandon Atom extensions. It's totally unuseful and buggy now. We even removed it from our page https://platformio.org/platformio-ide

PlatformIO Users, please switch to VSCode. We have released recently huge update to our extension for VSCode: https://community.platformio.org/t/massive-release-of-platformio-ide-for-vscode/4929
